kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: template-data-pvc-csi
  namespace: minecraft
spec:
  storageClassName: nfs-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
