apiVersion: v1
kind: Service
metadata:
  name: template
  namespace: minecraft
  labels:
    app: template
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  selector:
    app: template