name: Deploy to Kubernetes

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "self-hosted"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - id: 'upload-files'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'build/libs/'
          destination: 'INSERT_BUCKET**/template/plugins'
          glob: '*.jar'
          parent: false
  deploy:
    needs: build
    runs-on: "self-hosted" 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy App(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f kubernetes/stateful-set.yaml --force

      - name: Deploy PVC
        uses: actions-hub/kubectl@master
        with:
          args: apply -f kubernetes/csi-volume-claim.yaml

      - name: Apply Load Balancer
        uses: actions-hub/kubectl@master
        with:
          args: apply -f kubernetes/service-loadbalancer.yaml

      - name: Restart statefulset
        uses: actions-hub/kubectl@master
        with:
          args: rollout restart statefulset template -n minecraft
